import "~/styles/globals.css";
import { Inter } from "next/font/google";
import { twMerge } from "tailwind-merge";
import Navbar from "~/components/ui/navbar";
import { navItemsMannschaften, navItemsVeranstaltungen } from "./server-config";

export const revalidate = 43200 // Half a day

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Hockey Club Königs Wusterhausen 1966 e.V.",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          "bg-background font-sans text-foreground lg:flex",
          inter.variable,
        )}
      >
        <Navbar navItemsMannschaften={await navItemsMannschaften()} navItemsVeranstaltungen={await navItemsVeranstaltungen()} />
        <div className="mt-5 lg:mt-24">
          {children}
        </div>
      </body>
    </html>
  );
}
